version: '3'

services: 

    #Django Application
    django:
        image: django_dev_app:0.0.2
        build: 
            context: .
            dockerfile: Dockerfile.dev
        container_name: django_dev_server
        volumes: 
            - .:/app
        ports: 
            - "8000:8000"
        # env_file: 
        #     - ./.env
        environment: 
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0        
        command: python manage.py runserver 0.0.0.0:8000
        networks:
            - backend-net  

    # Celery
    # celery:
    #     container_name: celery
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile.dev    
    #     volumes: 
    #         - .:/app
    #     command: celery -A core worker -l DEBUG
        # networks:
        #     - backend-net  

networks:
    backend-net:
        external: true
        name: web-app-kp7-backend-network    
            
    




    
        
